name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/node.yml
      - libs/*
      - package.json
      - package-lock.json
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/node.yml
      - libs/*
      - package.json
      - package-lock.json
  workflow_dispatch:

jobs:
  build-library:
    name: build (${{ matrix.workspace }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace:
          - node-esbuild-js-cjs
          - node-esbuild-js-esm
          - node-esbuild-ts-esm
          - node-parcel-js-cjs
          - node-parcel-ts-esm
          - node-parcel-ts-esm
          - node-rollup-js-cjs
          - node-rollup-ts-esm
          - node-rollup-js-esm
          - node-tsup-js-cjs
          - node-tsup-js-esm
          - node-tsup-ts-esm
          - node-vite-js-cjs
          - node-vite-ts-esm
          - node-vite-js-esm
          - node-tsup-ts-esm
          - node-webpack-js-cjs
          - node-webpack-js-esm
          - node-webpack-ts-esm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js (latest)
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build library, run publint
        working-directory: ./libs/${{ matrix.workspace }}
        run: npm run publint
