name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/node.yml
      - libs/*
      - package.json
      - package-lock.json
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/node.yml
      - libs/*
      - package.json
      - package-lock.json
  workflow_dispatch:

jobs:
  build-library:
    name: build (${{ matrix.workspace }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace:
          - node-js-cjs-esbuild
          - node-js-cjs-parcel
          - node-js-cjs-rollup
          - node-js-cjs-vite
          - node-js-cjs-webpack
          - node-ts-esm-esbuild
          - node-ts-esm-parcel
          - node-ts-esm-rollup
          - node-ts-esm-vite
          - node-ts-esm-webpack
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js (latest)
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build library, run publint
        working-directory: ./libs/${{ matrix.workspace }}
        run: npm run publint
